[package]
name = "shetabit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
event-observer = { path = "../event-observer" }
reqwest = { version = "0.11", features = ["json"] }
